kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: amq-streams-lab
  namespace: kafka-cluster-2
spec:
  kafka:
    version: 3.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9095
        tls: true
        type: route
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.6'
    storage:
      type: jbod
      volumes:
        - deleteClaim: false
          id: 0
          size: 20Gi
          type: persistent-claim
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
  entityOperator:
    topicOperator: {}
    userOperator: {}
